[versions]
agp = "9.4.1"
androidImageCropper = "4.5.0"
androidPdfViewer = "3.2.0-beta06"
autoImageSlider = "1.0.1"
coil = "2.7.0"
firebaseBom = "34.19.0"
coreKtx = "1.19.0"
appcompat = "1.8.0"
material = "1.14.0"
activity = "1.13.0"
fragment = "1.9.0"
materialRipple = "1.0.1"
bubbleBottom = "1.0.2"
playServicesAds = "25.5.0"
googleServices = "4.5.0"
multicolors = "1.0.10"
lifecycle = "2.11.0"
hilt = "2.60.1"
coroutines = "1.11.0"
timber = "5.0.1"
navigation = "2.10.1"
room = "2.8.5"
cloudinary = "3.1.2"
ksp = "2.3.12"
kotlin = "2.4.20"

[libraries]
android-image-cropper = { module = "com.github.CanHub:Android-Image-Cropper", version.ref = "androidImageCropper" }
android-pdf-viewer = { module = "io.github.oothp:android-pdf-viewer", version.ref = "androidPdfViewer" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
autoimageslider = { module = "io.github.selimdawa:auto-image-slider", version.ref = "autoImageSlider" }
firebase-auth = { module = "com.google.firebase:firebase-auth" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
firebase-database = { module = "com.google.firebase:firebase-database" }
cloudinary-android = { module = "com.cloudinary:cloudinary-android", version.ref = "cloudinary" }
coil = { module = "io.coil-kt:coil", version.ref = "coil" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-fragment-ktx = { group = "androidx.fragment", name = "fragment-ktx", version.ref = "fragment" }
multicolors = { module = "com.github.selimdawa:MultiColors", version.ref = "multicolors" }
material-ripple = { module = "io.github.selimdawa:material-ripple-effect", version.ref = "materialRipple" }
bubblebottom = { module = "io.github.selimdawa:bubble-bottom", version.ref = "bubbleBottom" }
play-services-ads = { module = "com.google.android.gms:play-services-ads", version.ref = "playServicesAds" }
#MVVM
androidx-lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
#Hilt
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hilt" }
#Coroutines
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines" }
kotlinx-coroutines-play-services = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-play-services", version.ref = "coroutines" }
#Navigation
androidx-navigation-fragment-ktx = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigation" }
androidx-navigation-ui-ktx = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "navigation" }
#Room
androidx-room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
#Timber
timber = { group = "com.jakewharton.timber", name = "timber", version.ref = "timber" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
google-services = { id = "com.google.gms.google-services", version.ref = "googleServices" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
navigation-safeargs = { id = "androidx.navigation.safeargs.kotlin", version.ref = "navigation" }
kotlinParcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }